### ISSUE TITLE
Scraper keeps timing out, even after adding extra memory.

### ISSUE THREAD

**Issue by FunBinge** [tugkan/facebookads-scraper#1]
I've tried to run it multiple times (See screenshot attached) and I have also upgraded my account to use extra memory but it still fails. Any help is appreciated. 

This is what I see on the logs:  

`2022-01-14T05:30:35.537Z ACTOR: Pulling Docker image from repository.
2022-01-14T05:30:37.201Z ACTOR: Creating Docker container.
2022-01-14T05:30:37.555Z ACTOR: Starting Docker container.
2022-01-14T05:30:39.986Z INFO  System info {"apifyVersion":"2.1.0","apifyClientVersion":"2.0.2","osType":"Linux","nodeVersion":"v16.13.1"}
2022-01-14T05:30:39.992Z INFO  PHASE -- STARTING ACTOR.
2022-01-14T05:30:41.665Z         ==========================================================
2022-01-14T05:30:41.663Z INFO
2022-01-14T05:30:41.669Z         REMINDER: RESIDENTIAL proxies are required to use this actor
2022-01-14T05:30:41.672Z 
2022-01-14T05:30:41.671Z         ==========================================================
2022-01-14T05:30:41.752Z INFO  PHASE -- SETTING UP CRAWLER.
2022-01-14T05:30:41.814Z INFO  CRAWLER STARTED.
2022-01-14T05:30:41.869Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2022-01-14T05:31:12.209Z             rejectCallback(new Errors_js_1.TimeoutError('Timeout exceeded while waiting for event'));
2022-01-14T05:31:12.211Z                            ^
2022-01-14T05:31:12.213Z 
2022-01-14T05:31:12.207Z /home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:120
2022-01-14T05:31:12.215Z TimeoutError: Timeout exceeded while waiting for event
2022-01-14T05:31:12.217Z     at Timeout.<anonymous> (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:120:28)
2022-01-14T05:31:12.218Z     at listOnTimeout (node:internal/timers:557:17)
2022-01-14T05:31:12.222Z     at processTimers (node:internal/timers:500:7)
2022-01-14T05:31:12.361Z 
`
![Screen Shot 2022-01-14 at 4 03 05 pm](https://user-images.githubusercontent.com/8146906/149457171-7fd67d93-424b-4294-b88b-61c7e1bae757.png)

**Comment by tugkan** [comment]
Hey there @FunBinge ! 

Thank you very much for reporting this. Usually timeouts are related with the proxies but not the memory. So it'd be better for you to keep the memory around 4GBs (for optimization and cost purposes). Just to be sure, what kind of proxies that you are using? Are they Residential or Data Center proxies? Because for me everything is working fine with the Residential.

Best.

**Comment by FunBinge** [comment]
Hi @tugkan thank you for getting back to me on this. I am using a Residential proxy in Australia.
![Screen Shot 2022-01-16 at 9 51 11 am](https://user-images.githubusercontent.com/8146906/149640847-f1e4a397-579d-4e7e-8871-a2beeb92633e.png)

**Comment by FunBinge** [comment]
@tugkan you were right it seems it was the proxy. I just used a custom proxy but now I get the following error:

`2022-01-15T23:39:24.726Z ACTOR: Pulling Docker image from repository.
2022-01-15T23:39:35.018Z ACTOR: Creating Docker container.
2022-01-15T23:39:40.136Z ACTOR: Starting Docker container.
2022-01-15T23:39:43.799Z INFO  System info {"apifyVersion":"2.1.0","apifyClientVersion":"2.0.2","osType":"Linux","nodeVersion":"v16.13.1"}
2022-01-15T23:39:43.807Z INFO  PHASE -- STARTING ACTOR.
2022-01-15T23:39:45.514Z INFO
2022-01-15T23:39:45.537Z         ==========================================================
2022-01-15T23:39:45.571Z         REMINDER: RESIDENTIAL proxies are required to use this actor
2022-01-15T23:39:45.582Z         ==========================================================
2022-01-15T23:39:45.592Z 
2022-01-15T23:39:45.596Z INFO  PHASE -- SETTING UP CRAWLER.
2022-01-15T23:39:45.605Z INFO  CRAWLER STARTED.
2022-01-15T23:39:45.721Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2022-01-15T23:39:47.765Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.facebook.com/ads/library/?active_status=all&ad_type=all&country=US&view_all_page_id=101997995356880&search_type=page&media_type=all","retryCount":1,"id":"7p5uRFH9jh2f3of"}
2022-01-15T23:39:47.770Z   Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.facebook.com/ads/library/?active_status=all&ad_type=all&country=US&view_all_page_id=101997995356880&search_type=page&media_type=all
2022-01-15T23:39:47.774Z       at navigate (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:116:23)
2022-01-15T23:39:47.778Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-15T23:39:47.782Z       at async FrameManager.navigateFrame (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:21)
2022-01-15T23:39:47.786Z       at async Frame.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
2022-01-15T23:39:47.790Z       at async Page.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1156:16)
2022-01-15T23:39:47.794Z       at async PuppeteerCrawler._handleNavigation (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:362:40)
2022-01-15T23:39:47.798Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:317:13)
2022-01-15T23:39:47.806Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:409:17)
2022-01-15T23:39:47.802Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:432:13)
2022-01-15T23:39:48.034Z /home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1222
2022-01-15T23:39:48.048Z             this._disconnectPromise = new Promise((fulfill) => this._client.once(Connection_js_1.CDPSessionEmittedEvents.Disconnected, () => fulfill(new Error('Target closed'))));
2022-01-15T23:39:48.056Z 
2022-01-15T23:39:48.052Z                                                                                                                                                      ^
2022-01-15T23:39:48.060Z Error: Target closed
2022-01-15T23:39:48.065Z     at /home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1222:150
2022-01-15T23:39:48.071Z     at onceHandler (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:83:13)
2022-01-15T23:39:48.075Z     at /home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
2022-01-15T23:39:48.079Z     at Array.map (<anonymous>)
2022-01-15T23:39:48.085Z     at Object.emit (/home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
2022-01-15T23:39:48.090Z     at CDPSession.emit (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
2022-01-15T23:39:48.095Z     at CDPSession._onClosed (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:256:14)
2022-01-15T23:39:48.099Z     at Connection._onMessage (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:99:25)
2022-01-15T23:39:48.104Z     at WebSocket.<anonymous> (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
2022-01-15T23:39:48.108Z     at WebSocket.onMessage (/home/myuser/node_modules/puppeteer/node_modules/ws/lib/event-target.js:132:16)
2022-01-15T23:39:48.885Z 
`

**Comment by FunBinge** [comment]
Hi @tugkan thank you for your help, you were right, it was the proxy. Using a custom proxy worked :)

**Comment by tugkan** [comment]
It is great to hear that @FunBinge !
